import { useState } from "react";
import { Rocket, Copy, Check, Trash2, ChevronDown, ChevronRight } from "lucide-react";
import { type ReleaseNote } from "@/lib/store";

interface Props {
  notes: ReleaseNote[];
  onUpdate: (notes: ReleaseNote[]) => void;
}

export default function ReleaseNotesTab({ notes, onUpdate }: Props) {
  const [version, setVersion] = useState("");
  const [releaseDate, setReleaseDate] = useState(new Date().toISOString().split("T")[0]);
  const [features, setFeatures] = useState("");
  const [bugFixes, setBugFixes] = useState("");
  const [knownIssues, setKnownIssues] = useState("");
  const [copied, setCopied] = useState(false);
  const [expandedHistory, setExpandedHistory] = useState<Record<string, boolean>>({});

  const generateText = () => {
    const lines = [
      `📦 *Release Notes — v${version || "X.X.X"}*`,
      `📅 Date: ${releaseDate}`,
      "",
    ];
    if (features.trim()) {
      lines.push("✨ *New Features:*");
      features.split("\n").filter(Boolean).forEach((f) => lines.push(`  • ${f.trim()}`));
      lines.push("");
    }
    if (bugFixes.trim()) {
      lines.push("🐛 *Bug Fixes:*");
      bugFixes.split("\n").filter(Boolean).forEach((f) => lines.push(`  • ${f.trim()}`));
      lines.push("");
    }
    if (knownIssues.trim()) {
      lines.push("⚠️ *Known Issues:*");
      knownIssues.split("\n").filter(Boolean).forEach((f) => lines.push(`  • ${f.trim()}`));
      lines.push("");
    }
    lines.push("—");
    lines.push("Generated by HMS QA HUB");
    return lines.join("\n");
  };

  const handleGenerateAndCopy = () => {
    if (!version.trim()) return;
    const text = generateText();
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);

    // Save to history
    const newNote: ReleaseNote = {
      id: crypto.randomUUID(),
      version,
      releaseDate,
      features,
      bugFixes,
      knownIssues,
      createdAt: new Date().toISOString(),
    };
    onUpdate([newNote, ...notes]);

    // Reset form
    setVersion("");
    setReleaseDate(new Date().toISOString().split("T")[0]);
    setFeatures("");
    setBugFixes("");
    setKnownIssues("");
  };

  const handleDelete = (id: string) => {
    onUpdate(notes.filter((n) => n.id !== id));
  };

  const preview = generateText();

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-xl font-bold text-foreground flex items-center gap-2">
          <Rocket size={22} className="text-primary" />
          Release Note Generator
        </h2>
        <p className="text-sm text-muted-foreground">Generate professional release notes for WA/Slack</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Form */}
        <div className="bg-card rounded-xl border border-border p-5 shadow-sm space-y-4">
          <h3 className="font-semibold text-foreground text-sm">📝 Input</h3>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="text-sm font-medium text-foreground mb-1 block">Version *</label>
              <input
                value={version}
                onChange={(e) => setVersion(e.target.value)}
                placeholder="1.0.0"
                className="w-full px-3 py-2 rounded-lg border border-input bg-background text-foreground text-sm focus:outline-none focus:ring-2 focus:ring-ring"
              />
            </div>
            <div>
              <label className="text-sm font-medium text-foreground mb-1 block">Release Date</label>
              <input
                type="date"
                value={releaseDate}
                onChange={(e) => setReleaseDate(e.target.value)}
                className="w-full px-3 py-2 rounded-lg border border-input bg-background text-foreground text-sm focus:outline-none focus:ring-2 focus:ring-ring"
              />
            </div>
          </div>
          <div>
            <label className="text-sm font-medium text-foreground mb-1 block">✨ Features (one per line)</label>
            <textarea
              value={features}
              onChange={(e) => setFeatures(e.target.value)}
              placeholder="Add user profile page&#10;Implement dark mode"
              rows={3}
              className="w-full px-3 py-2 rounded-lg border border-input bg-background text-foreground text-sm focus:outline-none focus:ring-2 focus:ring-ring resize-none"
            />
          </div>
          <div>
            <label className="text-sm font-medium text-foreground mb-1 block">🐛 Bug Fixes (one per line)</label>
            <textarea
              value={bugFixes}
              onChange={(e) => setBugFixes(e.target.value)}
              placeholder="Fix login timeout issue&#10;Resolve data sync error"
              rows={3}
              className="w-full px-3 py-2 rounded-lg border border-input bg-background text-foreground text-sm focus:outline-none focus:ring-2 focus:ring-ring resize-none"
            />
          </div>
          <div>
            <label className="text-sm font-medium text-foreground mb-1 block">⚠️ Known Issues (one per line)</label>
            <textarea
              value={knownIssues}
              onChange={(e) => setKnownIssues(e.target.value)}
              placeholder="Slow loading on low-end devices"
              rows={2}
              className="w-full px-3 py-2 rounded-lg border border-input bg-background text-foreground text-sm focus:outline-none focus:ring-2 focus:ring-ring resize-none"
            />
          </div>
          <button
            onClick={handleGenerateAndCopy}
            disabled={!version.trim()}
            className="w-full flex items-center justify-center gap-2 px-4 py-2.5 text-sm rounded-lg bg-primary text-primary-foreground hover:bg-primary/90 transition-colors disabled:opacity-50"
          >
            {copied ? <Check size={16} /> : <Copy size={16} />}
            {copied ? "Copied to Clipboard!" : "Generate & Copy"}
          </button>
        </div>

        {/* Live Preview */}
        <div className="bg-card rounded-xl border border-border p-5 shadow-sm">
          <h3 className="font-semibold text-foreground text-sm mb-3">👁 Live Preview</h3>
          <pre className="text-sm text-foreground bg-muted rounded-lg p-4 whitespace-pre-wrap font-mono leading-relaxed overflow-auto max-h-[500px]">
            {preview}
          </pre>
        </div>
      </div>

      {/* History */}
      {notes.length > 0 && (
        <div className="bg-card rounded-xl border border-border p-5 shadow-sm">
          <h3 className="font-semibold text-foreground text-sm mb-3">📜 Release History</h3>
          <div className="space-y-2">
            {notes.map((note) => (
              <div key={note.id} className="border border-border rounded-lg">
                <button
                  onClick={() => setExpandedHistory({ ...expandedHistory, [note.id]: !expandedHistory[note.id] })}
                  className="w-full flex items-center justify-between p-3 text-sm hover:bg-muted/50 transition-colors"
                >
                  <div className="flex items-center gap-3">
                    {expandedHistory[note.id] ? <ChevronDown size={14} /> : <ChevronRight size={14} />}
                    <span className="font-medium text-foreground">v{note.version}</span>
                    <span className="text-muted-foreground">{note.releaseDate}</span>
                  </div>
                  <button
                    onClick={(e) => { e.stopPropagation(); handleDelete(note.id); }}
                    className="p-1 rounded hover:bg-muted text-destructive"
                  >
                    <Trash2 size={14} />
                  </button>
                </button>
                {expandedHistory[note.id] && (
                  <div className="px-3 pb-3">
                    <pre className="text-xs text-muted-foreground bg-muted rounded p-3 whitespace-pre-wrap font-mono">
                      {(() => {
                        const lines = [`📦 *Release Notes — v${note.version}*`, `📅 Date: ${note.releaseDate}`, ""];
                        if (note.features) { lines.push("✨ *New Features:*"); note.features.split("\n").filter(Boolean).forEach((f) => lines.push(`  • ${f.trim()}`)); lines.push(""); }
                        if (note.bugFixes) { lines.push("🐛 *Bug Fixes:*"); note.bugFixes.split("\n").filter(Boolean).forEach((f) => lines.push(`  • ${f.trim()}`)); lines.push(""); }
                        if (note.knownIssues) { lines.push("⚠️ *Known Issues:*"); note.knownIssues.split("\n").filter(Boolean).forEach((f) => lines.push(`  • ${f.trim()}`)); }
                        return lines.join("\n");
                      })()}
                    </pre>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
